
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package evaluacion;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRINGLITERAL = 3;
  public static final int error = 1;
  public static final int IDENTIFIER = 4;
  public static final int DOSPUNTOS = 2;
  public static final int PUNTOCOMA = 5;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOSPUNTOS",
  "STRINGLITERAL",
  "IDENTIFIER",
  "PUNTOCOMA"
  };
}

