
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package practica1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEPARACION = 11;
  public static final int PUNTO = 17;
  public static final int DOSPUNTOS = 19;
  public static final int POSITIVA = 9;
  public static final int IDENTIFIER = 4;
  public static final int BARRA = 13;
  public static final int CONDICIONAL = 8;
  public static final int LLAVEB = 16;
  public static final int LLAVEA = 15;
  public static final int VINETA = 6;
  public static final int COMA = 7;
  public static final int EOF = 0;
  public static final int COMILLAESP = 12;
  public static final int KLEEN = 14;
  public static final int CONJ = 20;
  public static final int COMILLA = 3;
  public static final int ARROW = 18;
  public static final int error = 1;
  public static final int ESPECIAL = 5;
  public static final int INTEGER_LITERAL = 2;
  public static final int PUNTOCOMA = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER_LITERAL",
  "COMILLA",
  "IDENTIFIER",
  "ESPECIAL",
  "VINETA",
  "COMA",
  "CONDICIONAL",
  "POSITIVA",
  "PUNTOCOMA",
  "SEPARACION",
  "COMILLAESP",
  "BARRA",
  "KLEEN",
  "LLAVEA",
  "LLAVEB",
  "PUNTO",
  "ARROW",
  "DOSPUNTOS",
  "CONJ"
  };
}

